#include "lipi.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static void collect_node(LipiCompiler *c, LipiAst *node) {
    if (!node) return;
    if (node->kind == AST_LIST && node->as.items.len == 3 &&
        lipi_ast_is_symbol((LipiAst *)node->as.items.items[0], "#inline") &&
        lipi_ast_is_symbol((LipiAst *)node->as.items.items[1], "c") &&
        ((LipiAst *)node->as.items.items[2])->kind == AST_BLOCK) {
        lipi_vec_push(&c->inline_c, ((LipiAst *)node->as.items.items[2])->as.text);
        return;
    }
    if (node->kind == AST_LIST || node->kind == AST_ARRAY || node->kind == AST_MAP) {
        for (int i = 0; i < node->as.items.len; i++) {
            collect_node(c, (LipiAst *)node->as.items.items[i]);
        }
    }
}

int lipi_collect_inline_c(LipiCompiler *c) {
    c->inline_c.len = 0;
    for (int i = 0; i < c->forms.len; i++) {
        collect_node(c, (LipiAst *)c->forms.items[i]);
    }
    return c->inline_c.len;
}

int lipi_compile_inline_c(LipiCompiler *c, const char *tmpdir, char *obj_path, size_t obj_path_cap) {
    if (c->inline_c.len == 0) {
        if (obj_path_cap) obj_path[0] = 0;
        return 0;
    }

    char c_path[1024];
    snprintf(c_path, sizeof(c_path), "%s/inline.c", tmpdir);
    snprintf(obj_path, obj_path_cap, "%s/inline.o", tmpdir);

    FILE *f = fopen(c_path, "wb");
    if (!f) {
        perror(c_path);
        return -1;
    }
    fputs("/* generated by lipi from #inline c blocks */\n", f);
    for (int i = 0; i < c->inline_c.len; i++) {
        fputs((char *)c->inline_c.items[i], f);
        fputc('\n', f);
    }
    fclose(f);

    const char *cc = getenv("CC");
    if (!cc || !cc[0]) {
        cc = "cc";
    }
    char *argv[] = { (char *)cc, "-I", (char *)(c->stdlib_path ? c->stdlib_path : "lib"),
                     "-c", c_path, "-o", obj_path, NULL };
    return lipi_run(argv) == 0 ? 1 : -1;
}
