name: CMake

on: [ push, pull_request, workflow_dispatch ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure CMake
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON

      - name: Build
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: cmake --build . --config $BUILD_TYPE

      - name: Test
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: ctest -C $BUILD_TYPE

      - name: Create Artifact
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: |-
          DESTDIR=$PWD/dest cmake --install . --prefix /usr

      - name: Pack Artifact
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: ${{github.workspace}}/build/${{matrix.os}}.zip
          directory: ${{github.workspace}}/build/dest

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{github.workspace}}/build/${{matrix.os}}.zip
          asset_name: srclang-${{matrix.os}}.zip
          tag: continuous
          overwrite: true
          prerelease: true
